- name: Install duplicity repository
  apt_repository:
    repo: ppa:duplicity-team/ppa
    state: present

- name: Install duplicity
  apt:
    name: duplicity
    state: latest

- name: Create duplicity profile directories
  file:
    path: "/etc/duplicity/{{item.name}}"
    state: directory
  with_items: duplicity_profiles

- name: Add profile duplicity script
  template:
    src: duplicity.sh.j2
    dest: "/etc/duplicity/{{item.name}}/duplicity.sh"
    mode: 0770
  with_items: duplicity_profiles

- name: Add profile includes
  template:
    src: include.j2
    dest: "/etc/duplicity/{{item.name}}/include"
  with_items: duplicity_profiles

- name: Add profile pre task
  template:
    src: "pre/{{item.pre_task}}.sh.j2"
    dest: "/etc/duplicity/{{item.name}}/pre.sh"
    mode: 0770
  when: item.pre_task is defined
  with_items: duplicity_profiles

- name: Add profile post task
  template:
    src: "post/{{item.post_task}}.sh.2"
    dest: "/etc/duplicity/{{item.name}}/post.sh"
    mode: 0770
  when: item.post_task is defined
  with_items: duplicity_profiles

#- name: Add cronjobs
#  cron:
#    name: "duplicity {{item.name}}"
#    job: "/bin/bash /etc/duplicity/{{item.name}}/duplicity.sh"
#    special_time: "{{item.special_time}}"
#    state: present
#  with_items: duplicity_profiles

- name: Add b2backend (bugfix)
  template:
    src: b2backend.py.j2
    dest: /usr/lib/python2.7/dist-packages/duplicity/backends/b2backend.py
