- name: Install apt
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt
    - apt-utils
    - python-apt
    - aptitude

- name: Install repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: apt_install_repositories

- name: Remove repositories
  apt_repository:
    repo: "{{ item }}"
    state: absent
  with_items: apt_remove_repositories

#- name: Upgrade packages
#  apt:
#    upgrade: safe

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_flattened:
    - apt_install
    - apt_install_host

- name: Remove packages
  apt:
    name: "{{ item }}"
    state: absent
  with_flattened:
    - apt_remove
    - apt_remove_host
