apt_install_repositories: []

apt_remove_repositories: []

apt_install:
  - rsync
  - curl
  - git
  - python
  - nano-tiny
  - wget
  - zip
  - unzip

apt_install_host: []

apt_remove: []

apt_remove_host: []
