---

- name: Make sure all groups are present
  group:
    name: "{{ item.name }}"
    system: "{{ item.system | default(omit) }}"
    gid: "{{ item.gid | default(omit) }}"
    state: present
  with_items: users_groups

- name: Create groups defined in users
  group:
    name: "{{ item.group | default(item.name) }}"
  with_items: users_users

- name: Make sure the users are present
  user:
    name: "{{ item.name }}"
    group: "{{ item.group | default(item.name) }}"
    groups: "{{ ','.join(item.groups) }}"
    append: "{{ item.append | default(omit) }}"
    password: "{{ item.pass | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    state: present
  with_items: users_users

- name: Install the authroized keys for the users
  authorized_key:
    user: "{{item.0.name}}"
    key: "{{item.1}}"
  with_subelements:
    - users_users
    - ssh_keys

- name: Make sure all removed users are not present
  user:
    name: "{{item.name}}"
    state: absent
    remove: yes
  with_items: users_users_removed

- name: Make sure all removed groups are not present
  group:
    name: "{{ item.name }}"
    state: absent
  with_items: users_groups_removed
